# Generated by Django 4.1.4 on 2023-01-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client", options={"verbose_name": "Client"},
        ),
    ]
