# Generated by Django 4.1.4 on 2022-12-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_signed", models.BooleanField(default=False)),
                (
                    "contract_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contract.contract",
                    ),
                ),
            ],
        ),
    ]
