# Generated by Django 4.1.4 on 2023-01-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contract_status", "0002_alter_contratstatus_options"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contract_status.contratstatus",
            ),
        ),
    ]
