# Generated by Django 4.1.4 on 2023-01-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contratstatus", options={"verbose_name": "Contrat status"},
        ),
    ]
